In [64]:
import numpy as np
import pandas as pd

In [65]:
# Load in movies dataset from parent directory

# movies = pd.read_csv('../ml-32m/movies.csv')
# ratings = pd.read_csv('../ml-32m/ratings.csv')
# movies.head()

# Code for 100k dataset:
ratings = pd.read_csv(
    "../ml-100k/u.data",
    sep="\t",
    names=["user_id", "movie_id", "rating", "timestamp"]
)

movies = pd.read_csv(
    "../ml-100k/u.item",
    sep="|",
    encoding="latin-1",
    header=None
)

# Name movies columns
movies = movies[[0, 1]]
movies.columns = ["movie_id", "title"]

print(movies.head())

   movie_id              title
0         1   Toy Story (1995)
1         2   GoldenEye (1995)
2         3  Four Rooms (1995)
3         4  Get Shorty (1995)
4         5     Copycat (1995)

In [66]:
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596

In [67]:
# Use this if files are uploaded on google drive:

'''
from google.colab import drive
drive.mount('/content/drive')

movies = pd.read_csv('../ml-32m/movies.csv')
ratings = pd.read_csv('../ml-32m/ratings.csv')
'''

"\nfrom google.colab import drive\ndrive.mount('/content/drive')\n\nmovies = pd.read_csv('../ml-32m/movies.csv')\nratings = pd.read_csv('../ml-32m/ratings.csv')\n"

In [68]:
# Ratings dataset is too big! Reduce to 400,000 rows (~2500 users)

ratings = ratings.sample(n=10000, random_state=42)

In [69]:
# Merge datasets on movie ID

df = ratings.merge(movies, on='movie_id')


# Create user-movie matrix

user_movie_matrix = df.pivot_table(
    index="user_id",
    columns="title",
    values="rating"
)

In [70]:
# Simple recommender function

def recommend_movies(movie_title, top_movies=10):

    # Get ratings for selected movie
    movie_ratings = user_movie_matrix[movie_title]

    # Find correlation between this movie and other
    similar_movies = user_movie_matrix.corrwith(movie_ratings)

    # Convert correlations to dataframe
    corr_df = pd.DataFrame(similar_movies, columns=["correlation"])

    # Sort correlations highest to lowest
    recommendations = corr_df.sort_values(by='correlation', ascending=False)

    # Remove the movie itself
    recommendations = recommendations.drop(movie_title, errors="ignore")

    # Return top movies
    return recommendations.head(top_movies)

In [71]:
# recommend_movies('Love Actually (2003)')

In [72]:
# Slightly more complicated recommender function

def recommend_movies(movie_title, top_movies=10):

    # Get ratings for selected movie
    movie_ratings = user_movie_matrix[movie_title]

    # Find correlation between this movie and other
    similar_movies = user_movie_matrix.corrwith(movie_ratings)

    # Convert correlations to dataframe
    corr_df = pd.DataFrame(similar_movies, columns=["correlation"])

    # Remove NaN values
    corr_df = corr_df.dropna()

    # Count number of ratings per movie
    rating_counts = df.groupby("title")["rating"].count()

    # Add rating counts
    corr_df["num_ratings"] = rating_counts

    # Filter out unpopular movies
    recommendations = corr_df[corr_df["num_ratings"] >= 30].sort_values(
        by="correlation",
        ascending=False)

    # Remove the movie itself
    recommendations = recommendations.drop(movie_title, errors="ignore")

    # Return top movies
    return recommendations.head(top_movies)

In [73]:
# recommend_movies("Rosemary's Baby (1968)")

In [74]:
# movie predictor

movie_corrs_df = user_movie_matrix.corr()

In [75]:
movie_corrs_df = movie_corrs_df.dropna()
movie_corrs_df.head()

Empty DataFrame
Columns: [1-900 (1994), 101 Dalmatians (1996), 12 Angry Men (1957), 187 (1997), 2 Days in the Valley (1996), 20,000 Leagues Under the Sea (1954), 2001: A Space Odyssey (1968), 3 Ninjas: High Noon At Mega Mountain (1998), 39 Steps, The (1935), 8 1/2 (1963), Absolute Power (1997), Abyss, The (1989), Ace Ventura: Pet Detective (1994), Ace Ventura: When Nature Calls (1995), Across the Sea of Time (1995), Addams Family Values (1993), Addicted to Love (1997), Adventures of Pinocchio, The (1996), Adventures of Priscilla, Queen of the Desert, The (1994), Adventures of Robin Hood, The (1938), African Queen, The (1951), Afterglow (1997), Age of Innocence, The (1993), Air Bud (1997), Air Force One (1997), Air Up There, The (1994), Airheads (1994), Akira (1988), Aladdin (1992), Aladdin and the King of Thieves (1996), Alaska (1996), Albino Alligator (1996), Alice in Wonderland (1951), Alien (1979), Alien 3 (1992), Alien: Resurrection (1997), Aliens (1986), All About Eve (1950), All Dogs Go to Heaven 2 (1996), Amadeus (1984), Amateur (1994), American President, The (1995), American Werewolf in London, An (1981), American in Paris, An (1951), Amistad (1997), Amityville Horror, The (1979), Amityville II: The Possession (1982), Amityville: A New Generation (1993), Amos & Andrew (1993), Anaconda (1997), Anastasia (1997), Andre (1994), Angela (1995), Angels and Insects (1995), Angels in the Outfield (1994), Angus (1995), Anna Karenina (1997), Anne Frank Remembered (1995), Annie Hall (1977), Another Stakeout (1993), Antonia's Line (1995), Apartment, The (1960), Apocalypse Now (1979), Apollo 13 (1995), Apostle, The (1997), Apple Dumpling Gang, The (1975), April Fool's Day (1986), Apt Pupil (1998), Aristocats, The (1970), Army of Darkness (1993), Around the World in 80 Days (1956), Arrival, The (1996), Arsenic and Old Lace (1944), As Good As It Gets (1997), Assassins (1995), Associate, The (1996), Audrey Rose (1977), Austin Powers: International Man of Mystery (1997), Ayn Rand: A Sense of Life (1997), B*A*P*S (1997), Babe (1995), Baby-Sitters Club, The (1995), Back to the Future (1985), Backbeat (1993), Bad Boys (1995), Bad Company (1995), Balto (1995), Bananas (1971), Band Wagon, The (1953), Barb Wire (1996), Barbarella (1968), Barcelona (1994), Basic Instinct (1992), Basketball Diaries, The (1995), Basquiat (1996), Bastard Out of Carolina (1996), Batman & Robin (1997), Batman (1989), Batman Forever (1995), Batman Returns (1992), ...]
Index: []

[0 rows x 1236 columns]

In [76]:
ratings = pd.read_csv(
    "../ml-100k/u.data",
    sep="\t",
    names=["user_id", "movie_id", "rating", "timestamp"]
)

In [77]:
ratings.head()

   user_id  movie_id  rating  timestamp
0      196       242       3  881250949
1      186       302       3  891717742
2       22       377       1  878887116
3      244        51       2  880606923
4      166       346       1  886397596